# Generated by Django 2.2 on 2021-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(2, 'Fail'), (1, 'Success'), (0, 'Waiting')], default=0)),
                ('transfer_style', models.SmallIntegerField(choices=[(0, 'wave'), (1, 'la_muse')], default=0)),
                ('org_buket', models.CharField(editable=False, max_length=100, null=True, unique=True)),
                ('new_buket', models.CharField(editable=False, max_length=100, null=True, unique=True)),
                ('key', models.CharField(editable=False, max_length=100, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
