# Generated by Django 2.2 on 2021-01-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transferrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrecord',
            old_name='org_buket',
            new_name='download_path',
        ),
    ]
