# Generated by Django 2.2 on 2021-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210112_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='new_buket',
            field=models.CharField(default='pre-image-after', editable=False, max_length=100, null=True),
        ),
    ]
