# Generated by Django 2.2 on 2021-01-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210112_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrecord',
            name='download_path',
        ),
    ]
