# Generated by Django 2.2 on 2021-01-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_transferrecord_download_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrecord',
            old_name='new_buket',
            new_name='new_bucket',
        ),
    ]
