# Generated by Django 2.2 on 2021-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210112_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecord',
            name='new_key',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='key',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transferrecord',
            name='transfer_style',
            field=models.SmallIntegerField(choices=[(0, 'wave'), (1, 'la_muse'), (2, 'rain_princess'), (3, 'the_scream'), (4, 'udnie'), (5, 'the_shipwreck_of_the_minotaur')], default=0),
        ),
    ]
