# Generated by Django 2.2 on 2021-01-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transferrecord_org_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='org_bucket',
            field=models.CharField(default='pre-image', editable=False, max_length=100, null=True),
        ),
    ]
