# Generated by Django 2.2 on 2021-01-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210113_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferrecord',
            old_name='key',
            new_name='old_key',
        ),
    ]
