# Generated by Django 2.2 on 2021-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210113_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'Fail'), (1, 'Success'), (0, 'Waiting'), (3, 'Doing')], default=0),
        ),
    ]
