# Generated by Django 2.2 on 2021-01-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210113_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
