# Generated by Django 2.2 on 2021-01-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210113_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrecord',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='transferrecord',
            name='update_at',
        ),
    ]
